// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'https://oknvpipzzgfufvqssauz.supabase.co'
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rbnZwaXB6emdmdWZ2cXNzYXV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NDI3NTEsImV4cCI6MjA2NzUxODc1MX0.gCkp0NyoWFaRlSQi6tKmb7R5p1BN_2HroZ6IuR7w7xY'

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
})